// Builds the installable web app (PWA) into docs/ for GitHub Pages
// (Settings → Pages → branch main, folder /docs).
//   node build-site.js            rebuilds pages, manifest, service worker
//   node build-site.js --icons    also re-renders the icons (needs swiftc + sips)
import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';

const root = new URL('./', import.meta.url);
const P = (p) => fileURLToPath(new URL(p, root));
const read = (p) => readFileSync(P(p), 'utf8');
const write = (p, s) => { writeFileSync(P(p), s); console.log('  wrote', p); };

// fresh root pages first (they also feed the artifacts and the Mac app)
execFileSync('node', [P('build-html.js')], { stdio: 'inherit' });
execFileSync('node', [P('build-game.js')], { stdio: 'inherit' });

mkdirSync(P('docs/icons'), { recursive: true });
const buildId = Date.now().toString(36);

const HEAD = (title) => `<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<title>${title}</title>
<link rel="manifest" href="./manifest.webmanifest">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Black Jack">
<meta name="theme-color" content="#E3E9E2" media="(prefers-color-scheme: light)">
<meta name="theme-color" content="#0D2A20" media="(prefers-color-scheme: dark)">
<link rel="apple-touch-icon" href="./icons/apple-touch-icon.png">
<link rel="icon" type="image/png" sizes="192x192" href="./icons/icon-192.png">`;

const SW_REG = `<script>try {
  if ('serviceWorker' in navigator && location.protocol === 'https:') {
    const hadController = !!navigator.serviceWorker.controller;
    navigator.serviceWorker.register('./sw.js');
    // a new version took over: tell the game so it can reload between rounds
    navigator.serviceWorker.addEventListener('controllerchange', () => { if (hadController) window.dispatchEvent(new Event('bj-update')); });
  }
} catch (e) { /* no offline support */ }</script>`;

// the root pages are body fragments (title + style + markup); wrap them in a full document
function toDocument(fragment, { nav = '' } = {}) {
  const title = (fragment.match(/<title>([^<]*)<\/title>/) || [, 'European Black Jack'])[1];
  const cut = fragment.indexOf('</style>') + '</style>'.length;
  const head = fragment.slice(0, cut).replace(/<title>[^<]*<\/title>\s*/, '').replace('<!--PWA-->', HEAD(title));
  const body = fragment.slice(cut).replace('<!--PWA-NAV-->', nav);
  return `<!doctype html>\n<html lang="lt">\n<head>\n${head}\n</head>\n<body>\n${body}\n${SW_REG}\n</body>\n</html>\n`;
}

console.log('→ site pages');
const game = read('zaidimas.html')
  .replace(/<a id="table-link" href="[^"]*" target="_blank" rel="noopener"/, '<a id="table-link" href="./lentele.html"');
write('docs/index.html', toDocument(game));
write('docs/lentele.html', toDocument(read('strategija.html'), {
  nav: '<a class="back" href="./index.html" data-i18n="back">← Žaidimas</a>',
}));

write('docs/manifest.webmanifest', JSON.stringify({
  name: 'European Black Jack',
  short_name: 'Black Jack',
  description: 'European Black Jack trainer with a live advisor',
  start_url: './index.html',
  scope: './',
  display: 'standalone',
  orientation: 'portrait',
  background_color: '#0D2A20',
  theme_color: '#0D2A20',
  icons: [
    { src: './icons/icon-192.png', sizes: '192x192', type: 'image/png', purpose: 'any' },
    { src: './icons/icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any' },
    { src: './icons/maskable-512.png', sizes: '512x512', type: 'image/png', purpose: 'maskable' },
  ],
}, null, 2) + '\n');

write('docs/sw.js', `// generated by build-site.js
const CACHE = 'bj-${buildId}';
const SHELL = ['./', './index.html', './lentele.html', './manifest.webmanifest',
  './icons/icon-192.png', './icons/icon-512.png', './icons/maskable-512.png', './icons/apple-touch-icon.png'];
const FONT_HOSTS = ['fonts.googleapis.com', 'fonts.gstatic.com'];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(SHELL)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys()
    .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
    .then(() => self.clients.claim()));
});
// stale-while-revalidate: answer from the cache, refresh it in the background
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET') return;
  const url = new URL(req.url);
  if (url.origin !== self.location.origin && !FONT_HOSTS.includes(url.hostname)) return;
  e.respondWith(caches.open(CACHE).then(async (cache) => {
    const cached = await cache.match(req);
    const network = fetch(req).then((res) => {
      if (res && (res.ok || res.type === 'opaque')) cache.put(req, res.clone());
      return res;
    }).catch(() => cached);
    return cached || network;
  }));
});
`);
write('docs/.nojekyll', '');

// icons: rounded/transparent for the manifest, full-bleed for iOS home screens
function makeIcons() {
  mkdirSync(P('dist'), { recursive: true });
  const bin = P('dist/make-icon');
  execFileSync('swiftc', ['-swift-version', '5', '-O', '-o', bin, P('app/make-icon.swift'), '-framework', 'AppKit']);
  execFileSync(bin, [P('dist/icon-1024.png')]);
  execFileSync(bin, [P('dist/icon-square-1024.png'), '--square']);
  const sips = (src, size, out) => execFileSync('sips', ['-z', String(size), String(size), src, '--out', out], { stdio: 'ignore' });
  sips(P('dist/icon-1024.png'), 192, P('docs/icons/icon-192.png'));
  sips(P('dist/icon-1024.png'), 512, P('docs/icons/icon-512.png'));
  sips(P('dist/icon-square-1024.png'), 512, P('docs/icons/maskable-512.png'));
  sips(P('dist/icon-square-1024.png'), 180, P('docs/icons/apple-touch-icon.png'));
  console.log('  wrote docs/icons/*');
}
const haveIcons = existsSync(P('docs/icons/apple-touch-icon.png'));
if (!haveIcons || process.argv.includes('--icons')) {
  try { makeIcons(); } catch (e) { if (!haveIcons) throw e; console.warn('icons not rebuilt:', e.message); }
}
console.log(`✓ docs/ ready (build ${buildId})`);
